provider: aws
aws:
  zoneType: public
  region: eu-west-2
policy: sync
txtOwnerId: external-dns
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
serviceAccount:
  create: true
