apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials-secret
  namespace: cert-manager
type: Opaque
data:
  access-key-id: QUtJQTZFTEtPQVc1TjVYQTNOVkk=
  secret-access-key: c3VhbHM0UlNydE56akNIRkRLN1lwbUZEWVB0WURaQzErU2tTR2t3Wg==

