apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: yhyhtwotwo@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          route53:
            region: eu-west-2  
            accessKeyID: AKIA6ELKOAW5N5XA3NVI
            secretAccessKeySecretRef:
              name: route53-credentials-secret
              key: secret-access-key

